<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-T6EF9OC" failures="1" tests="4" name="Test" time="3.633" errors="0" timestamp="2025-05-31T23:44:01 IST">
  <testcase classname="org.api.servicenow.chaining.PostWithRequestBodyAsFile" name="postWithRequestBodyAsFile" time="2.871">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at org.api.servicenow.chaining.PostWithRequestBodyAsFile.postWithRequestBodyAsFile(PostWithRequestBodyAsFile.java:34)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
... 32 more
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- postWithRequestBodyAsFile -->
  <testcase classname="org.api.servicenow.chaining.UpdateIncident" name="updateIncident" time="0.0">
    <skipped/>
  </testcase> <!-- updateIncident -->
  <testcase classname="org.api.servicenow.chaining.GetAllIncidentsWithMultipleQueryParams" name="getAllIncidentsWithMultipleQueryParams" time="0.0">
    <skipped/>
  </testcase> <!-- getAllIncidentsWithMultipleQueryParams -->
  <testcase classname="org.api.servicenow.chaining.DeleteIncident" name="deleteIncident" time="0.0">
    <skipped/>
  </testcase> <!-- deleteIncident -->
  <testcase classname="org.api.servicenow.chaining.BaseAPIClass" name="@BeforeTest preCondition" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest preCondition -->
  <testcase classname="org.api.servicenow.chaining.BaseAPIClass" name="@BeforeTest preCondition" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest preCondition -->
  <testcase classname="org.api.servicenow.chaining.BaseAPIClass" name="@BeforeTest preCondition" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest preCondition -->
</testsuite> <!-- Test -->
